spring.profiles.active=${SPRING_PROFILES_ACTIVE}
spring.application.name=user-service
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

spring.jpa.hibernate.ddl-auto=none

spring.cache.type=redis
spring.cache.redis.time-to-live=10m

