server.port=${APP_PORT}

spring.datasource.username=${L_DB_USERNAME}
spring.datasource.password=${L_DB_PASSWORD}
spring.datasource.url=jdbc:postgresql://localhost:${L_DB_HOST_PORT}/${L_DB_NAME}

spring.data.redis.host=localhost
spring.data.redis.port=${REDIS_PORT}