server.port=${APP_PORT:8081}

spring.datasource.username=${D_DB_USERNAME}
spring.datasource.password=${D_DB_PASSWORD}
spring.datasource.url=jdbc:postgresql://postgres-db:${D_DB_HOST_PORT}/${D_DB_NAME}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
